name: Selenide Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Maven tests with Selenide
        run: |
          docker run --name selenium -d -p 4444:4444 selenium/standalone-chrome:latest
          mvn test -Dwebdriver.chrome.driver=/usr/bin/chromedriver
        env:
          SE_OPTS: "-host localhost -port 4444"
